# Generated by Django 3.2.10 on 2022-01-04 10:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_newblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('person', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock()), ('surname', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(Required=False)), ('biography', wagtail.core.blocks.RichTextBlock())])), ('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
